# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
import pandas as pd

In [2]:
customer_data= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")

In [3]:
customer_data

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
4003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
customer_data.isna().sum()

Customer                     2937
ST                           2937
GENDER                       3054
Education                    2937
Customer Lifetime Value      2940
Income                       2937
Monthly Premium Auto         2937
Number of Open Complaints    2937
Policy Type                  2937
Vehicle Class                2937
Total Claim Amount           2937
dtype: int64

In [5]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [6]:
customer_data.dropna(axis=0, how="all")

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
1066,TM65736,Oregon,M,Master,305955.03%,38644.0,78.0,1/1/00,Personal Auto,Four-Door Car,361.455219
1067,VJ51327,Cali,F,High School or Below,2031499.76%,63209.0,102.0,1/2/00,Personal Auto,SUV,207.320041
1068,GS98873,Arizona,F,Bachelor,323912.47%,16061.0,88.0,1/0/00,Personal Auto,Four-Door Car,633.600000
1069,CW49887,California,F,Master,462680.11%,79487.0,114.0,1/0/00,Special Auto,SUV,547.200000
1070,MY31220,California,F,College,899704.02%,54230.0,112.0,1/0/00,Personal Auto,Two-Door Car,537.600000

In [7]:
customer_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4008 entries, 0 to 4007
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   1071 non-null   object
 1   ST                         1071 non-null   object
 2   GENDER                     954 non-null    object
 3   Education                  1071 non-null   object
 4   Customer Lifetime Value    1068 non-null   object
 5   Income                     1071 non-null   float64
 6   Monthly Premium Auto       1071 non-null   float64
 7   Number of Open Complaints  1071 non-null   object
 8   Policy Type                1071 non-null   object
 9   Vehicle Class              1071 non-null   object
 10  Total Claim Amount         1071 non-null   float64
dtypes: float64(3), object(8)
memory usage: 344.6+ KB

In [8]:
customer_data.columns = customer_data.columns.str.lower()

In [9]:
customer_data.head()

,customer,st,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [10]:
customer_data.columns=customer_data.columns.str.replace(" ","_")

In [11]:
customer_data.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [12]:
customer_data.rename(columns= {"st":"state"}, inplace=True)
customer_data.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [13]:
customer_data_1= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")

In [14]:
customer_data_1

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.600000,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.200000,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.600000,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.200000,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.200000,Corporate Auto,Two-Door Car
...,...,...,...,...,...,...,...,...,...,...,...
991,HV85198,Arizona,M,Master,847141.75%,63513,70,1/0/00,185.667213,Personal Auto,Four-Door Car
992,BS91566,Arizona,F,College,543121.91%,58161,68,1/0/00,140.747286,Corporate Auto,Four-Door Car
993,IL40123,Nevada,F,College,568964.41%,83640,70,1/0/00,471.050488,Corporate Auto,Two-Door Car
994,MY32149,California,F,Master,368672.38%,0,96,1/0/00,28.460568,Personal Auto,Two-Door Car
995,SA91515,California,M,Bachelor,399258.39%,0,111,1/0/00,700.349052,Personal Auto,SUV

In [15]:
customer_data_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 996 entries, 0 to 995
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   996 non-null    object
 1   ST                         996 non-null    object
 2   GENDER                     991 non-null    object
 3   Education                  996 non-null    object
 4   Customer Lifetime Value    992 non-null    object
 5   Income                     996 non-null    int64
 6   Monthly Premium Auto       996 non-null    int64
 7   Number of Open Complaints  996 non-null    object
 8   Total Claim Amount         996 non-null    float64
 9   Policy Type                996 non-null    object
 10  Vehicle Class              996 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 85.7+ KB

In [16]:
customer_data_1.isna().sum()

Customer                     0
ST                           0
GENDER                       5
Education                    0
Customer Lifetime Value      4
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Total Claim Amount           0
Policy Type                  0
Vehicle Class                0
dtype: int64

In [17]:
customer_data_1.dtypes

Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                         int64
Monthly Premium Auto           int64
Number of Open Complaints     object
Total Claim Amount           float64
Policy Type                   object
Vehicle Class                 object
dtype: object

In [18]:
customer_data_1_reordered = customer_data_1.iloc[:, [0, 1, 2,3,4,5,6,7,9,10,8]]

In [19]:
customer_data_1_reordered.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.2
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.2

In [20]:
customer_data_1_reordered.columns=customer_data_1_reordered.columns.str.lower()

In [21]:
customer_data_1_reordered.head()

,customer,st,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.2
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.2

In [22]:
customer_data_1_reordered.columns=customer_data_1_reordered.columns.str.replace(" ","_")

In [23]:
customer_data_1_reordered.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.2
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.2

In [24]:
customer_data_1_reordered.rename(columns={"st":"state"}, inplace=True)
customer_data_1_reordered.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,Personal Auto,Four-Door Car,633.6
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,Special Auto,SUV,547.2
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,Personal Auto,Two-Door Car,537.6
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,Personal Auto,Luxury Car,1027.2
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,Corporate Auto,Two-Door Car,451.2

In [25]:
customer_data_2=pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [26]:
customer_data_2.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [27]:
customer_data_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7070 entries, 0 to 7069
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   7070 non-null   object
 1   State                      7070 non-null   object
 2   Customer Lifetime Value    7070 non-null   float64
 3   Education                  7070 non-null   object
 4   Gender                     7070 non-null   object
 5   Income                     7070 non-null   int64
 6   Monthly Premium Auto       7070 non-null   int64
 7   Number of Open Complaints  7070 non-null   int64
 8   Policy Type                7070 non-null   object
 9   Total Claim Amount         7070 non-null   float64
 10  Vehicle Class              7070 non-null   object
dtypes: float64(2), int64(3), object(6)
memory usage: 607.7+ KB

In [28]:
customer_data_2.isna().sum()

Customer                     0
State                        0
Customer Lifetime Value      0
Education                    0
Gender                       0
Income                       0
Monthly Premium Auto         0
Number of Open Complaints    0
Policy Type                  0
Total Claim Amount           0
Vehicle Class                0
dtype: int64

In [29]:
customer_data_2_reordered=customer_data_2.iloc[:,[0,1,4,3,2,5,6,7,8,10,9]]

In [30]:
customer_data_2_reordered.head()

,Customer,State,Gender,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,SA25987,Washington,M,High School or Below,3479.137523,0,104,0,Personal Auto,Two-Door Car,499.200000
1,TB86706,Arizona,M,Master,2502.637401,0,66,0,Personal Auto,Two-Door Car,3.468912
2,ZL73902,Nevada,F,Bachelor,3265.156348,25820,82,0,Personal Auto,Four-Door Car,393.600000
3,KX23516,California,F,High School or Below,4455.843406,0,121,0,Personal Auto,SUV,699.615192
4,FN77294,California,M,High School or Below,7704.958480,30366,101,2,Personal Auto,SUV,484.800000

In [31]:
customer_data_2_reordered.columns=customer_data_2_reordered.columns.str.lower()

In [32]:
customer_data_2_reordered.head()

,customer,state,gender,education,customer lifetime value,income,monthly premium auto,number of open complaints,policy type,vehicle class,total claim amount
0,SA25987,Washington,M,High School or Below,3479.137523,0,104,0,Personal Auto,Two-Door Car,499.200000
1,TB86706,Arizona,M,Master,2502.637401,0,66,0,Personal Auto,Two-Door Car,3.468912
2,ZL73902,Nevada,F,Bachelor,3265.156348,25820,82,0,Personal Auto,Four-Door Car,393.600000
3,KX23516,California,F,High School or Below,4455.843406,0,121,0,Personal Auto,SUV,699.615192
4,FN77294,California,M,High School or Below,7704.958480,30366,101,2,Personal Auto,SUV,484.800000

In [33]:
customer_data_2_reordered.columns=customer_data_2_reordered.columns.str.replace(" ","_")

In [34]:
customer_data_2_reordered.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,SA25987,Washington,M,High School or Below,3479.137523,0,104,0,Personal Auto,Two-Door Car,499.200000
1,TB86706,Arizona,M,Master,2502.637401,0,66,0,Personal Auto,Two-Door Car,3.468912
2,ZL73902,Nevada,F,Bachelor,3265.156348,25820,82,0,Personal Auto,Four-Door Car,393.600000
3,KX23516,California,F,High School or Below,4455.843406,0,121,0,Personal Auto,SUV,699.615192
4,FN77294,California,M,High School or Below,7704.958480,30366,101,2,Personal Auto,SUV,484.800000

In [35]:
customer_data_master=pd.concat([customer_data, customer_data_1_reordered, customer_data_2_reordered], axis=0, ignore_index=True)

In [36]:
customer_data_master.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [37]:

customer_data_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.0+ MB

In [38]:
customer_data_master.shape

(12074, 11)

In [39]:
customer_data_master.isna().sum()

customer                     2937
state                        2937
gender                       3059
education                    2937
customer_lifetime_value      2944
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [40]:
customer_data_master=customer_data_master.dropna(axis=0, how="all")
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
12069,LA72316,California,M,Bachelor,23406,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
12070,PK87824,California,F,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
12071,TD14365,California,M,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
12072,UP19263,California,M,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
12073,Y167826,California,M,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [41]:
customer_data_master=customer_data_master.reset_index(drop=True)

In [42]:
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,M,Bachelor,23406,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,F,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,M,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,M,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,M,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [43]:
customer_data_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   object
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 785.3+ KB

In [44]:
customer_data_master['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', 'Cali',
       'AZ', 'WA'], dtype=object)

In [45]:
mapping_state={'Washington':'Washington','Arizona':'Arizona', 'Nevada':'Nevada', 'California':'California', 'Oregon':'Oregon', 'Cali':'California',
       'AZ':'Arizona', 'WA': 'Washington'}
customer_data_master['state']= customer_data_master['state'].map(mapping_state)
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,M,Bachelor,23406,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,F,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,M,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,M,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,M,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [46]:
customer_data_master['state'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon'],
      dtype=object)

In [47]:
customer_data_master['state'].dtypes

dtype('O')

In [48]:
customer_data_master['gender'].unique()

array([nan, 'F', 'M', 'Femal', 'Male', 'female'], dtype=object)

In [49]:
mapping_gender={'nan':'nan', 'F':'Female', 'M':'Male', 'Femal':'Female', 'Male':'Male', 'female':'Female'}
customer_data_master['gender'] = customer_data_master['gender'].map(mapping_gender)

In [50]:
customer_data_master.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,Female,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,Female,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [51]:
customer_data_master['gender'].unique()

array([nan, 'Female', 'Male'], dtype=object)

In [52]:
customer_data_master['gender'].value_counts()

Female    4607
Male      4408
Name: gender, dtype: int64

In [53]:
gender_mode=customer_data_master['gender'].mode()[0]
gender_mode

'Female'

In [54]:
customer_data_master['gender']=customer_data_master['gender'].fillna(gender_mode)
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,Female,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,Female,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,23406,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,Female,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,Male,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,Male,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,Male,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [55]:
customer_data_master['gender'].isna().sum()

0

In [56]:
customer_data_master['gender'].unique()

array(['Female', 'Male'], dtype=object)

In [57]:
customer_data_master['education'].unique()

array(['Master', 'Bachelor', 'High School or Below', 'College',
       'Bachelors', 'Doctor'], dtype=object)

In [58]:
customer_data_master['education']=customer_data_master['education'].str.replace('Bachelors', 'Bachelor')
print(customer_data_master['education'].unique())
customer_data_master

['Master' 'Bachelor' 'High School or Below' 'College' 'Doctor']

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,Female,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,Female,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,Male,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,Male,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,23406,71941.0,73.0,0,Personal Auto,Four-Door Car,198.234764
9133,PK87824,California,Female,College,3096.51,21604.0,79.0,0,Corporate Auto,Four-Door Car,379.200000
9134,TD14365,California,Male,Bachelor,8163.89,0.0,85.0,3,Corporate Auto,Four-Door Car,790.784983
9135,UP19263,California,Male,College,7524.44,21941.0,96.0,0,Personal Auto,Four-Door Car,691.200000
9136,Y167826,California,Male,College,2611.84,0.0,77.0,0,Corporate Auto,Two-Door Car,369.600000

In [59]:
customer_data_master['education'].isna().sum()

0

In [60]:
customer_data_master['customer_lifetime_value'].dtypes

dtype('O')

In [87]:
import numpy as np

pd.set_option("display.float_format", "{:,.2f}".format)
def clean_percentage(value):
    if isinstance(value, list):
        value = value[0] if value else np.nan

    if pd.isna(value) or value == "":
        return np.nan

    if "%" in str(value):
        value = str(value).split("%")[0]

    return float(value)

In [88]:
customer_data_master['customer_lifetime_value'] = (customer_data_master['customer_lifetime_value'].apply(clean_percentage))

In [89]:
customer_data_master['customer_lifetime_value'].isna().sum()

7

In [91]:
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,nan,0.00,"1,000.00",1/0/00,Personal Auto,Four-Door Car,2.70
1,QZ44356,Arizona,Female,Bachelor,"697,953.59",0.00,94.00,1/0/00,Personal Auto,Four-Door Car,"1,131.46"
2,AI49188,Nevada,Female,Bachelor,"1,288,743.17","48,767.00",108.00,1/0/00,Personal Auto,Two-Door Car,566.47
3,WW63253,California,Male,Bachelor,"764,586.18",0.00,106.00,1/0/00,Corporate Auto,SUV,529.88
4,GA49547,Washington,Male,High School or Below,"536,307.65","36,357.00",68.00,1/0/00,Personal Auto,Four-Door Car,17.27
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,"23,405.99","71,941.00",73.00,0,Personal Auto,Four-Door Car,198.23
9133,PK87824,California,Female,College,"3,096.51","21,604.00",79.00,0,Corporate Auto,Four-Door Car,379.20
9134,TD14365,California,Male,Bachelor,"8,163.89",0.00,85.00,3,Corporate Auto,Four-Door Car,790.78
9135,UP19263,California,Male,College,"7,524.44","21,941.00",96.00,0,Personal Auto,Four-Door Car,691.20
9136,Y167826,California,Male,College,"2,611.84",0.00,77.00,0,Corporate Auto,Two-Door Car,369.60

In [92]:
customer_data_master['number_of_open_complaints'].unique()

array(['1/0/00', '1/2/00', '1/1/00', '1/3/00', '1/5/00', '1/4/00', 0, 2,
       3, 1, 5, 4], dtype=object)

In [93]:
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,nan,0.00,"1,000.00",1/0/00,Personal Auto,Four-Door Car,2.70
1,QZ44356,Arizona,Female,Bachelor,"697,953.59",0.00,94.00,1/0/00,Personal Auto,Four-Door Car,"1,131.46"
2,AI49188,Nevada,Female,Bachelor,"1,288,743.17","48,767.00",108.00,1/0/00,Personal Auto,Two-Door Car,566.47
3,WW63253,California,Male,Bachelor,"764,586.18",0.00,106.00,1/0/00,Corporate Auto,SUV,529.88
4,GA49547,Washington,Male,High School or Below,"536,307.65","36,357.00",68.00,1/0/00,Personal Auto,Four-Door Car,17.27
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,"23,405.99","71,941.00",73.00,0,Personal Auto,Four-Door Car,198.23
9133,PK87824,California,Female,College,"3,096.51","21,604.00",79.00,0,Corporate Auto,Four-Door Car,379.20
9134,TD14365,California,Male,Bachelor,"8,163.89",0.00,85.00,3,Corporate Auto,Four-Door Car,790.78
9135,UP19263,California,Male,College,"7,524.44","21,941.00",96.00,0,Personal Auto,Four-Door Car,691.20
9136,Y167826,California,Male,College,"2,611.84",0.00,77.00,0,Corporate Auto,Two-Door Car,369.60

In [94]:
def clean_complaints(value):
    if "/" in str(value):
        return int(str(value).split("/")[1])
    else:
        return int(value)

In [95]:
customer_data_master["number_of_open_complaints"] = (customer_data_master["number_of_open_complaints"].apply(clean_complaints))

In [96]:
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,nan,0.00,"1,000.00",0,Personal Auto,Four-Door Car,2.70
1,QZ44356,Arizona,Female,Bachelor,"697,953.59",0.00,94.00,0,Personal Auto,Four-Door Car,"1,131.46"
2,AI49188,Nevada,Female,Bachelor,"1,288,743.17","48,767.00",108.00,0,Personal Auto,Two-Door Car,566.47
3,WW63253,California,Male,Bachelor,"764,586.18",0.00,106.00,0,Corporate Auto,SUV,529.88
4,GA49547,Washington,Male,High School or Below,"536,307.65","36,357.00",68.00,0,Personal Auto,Four-Door Car,17.27
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,"23,405.99","71,941.00",73.00,0,Personal Auto,Four-Door Car,198.23
9133,PK87824,California,Female,College,"3,096.51","21,604.00",79.00,0,Corporate Auto,Four-Door Car,379.20
9134,TD14365,California,Male,Bachelor,"8,163.89",0.00,85.00,3,Corporate Auto,Four-Door Car,790.78
9135,UP19263,California,Male,College,"7,524.44","21,941.00",96.00,0,Personal Auto,Four-Door Car,691.20
9136,Y167826,California,Male,College,"2,611.84",0.00,77.00,0,Corporate Auto,Two-Door Car,369.60

In [97]:
customer_data_master['number_of_open_complaints'].unique()

array([0, 2, 1, 3, 5, 4])

In [99]:
customer_data_master['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury SUV', 'Sports Car',
       'Luxury Car'], dtype=object)

In [100]:
mapping_vehicle={'Four-Door Car':'Four-Door Car', 'Two-Door Car':'Two-Door Car', 'SUV':'SUV', 'Luxury SUV':'Luxury', 'Sports Car':'Luxury',
       'Luxury Car':'Luxury'}

In [101]:
customer_data_master['vehicle_class']=customer_data_master['vehicle_class'].map(mapping_vehicle)

In [102]:
customer_data_master['vehicle_class'].unique()

array(['Four-Door Car', 'Two-Door Car', 'SUV', 'Luxury'], dtype=object)

In [103]:
customer_data_master['policy_type'].unique()

array(['Personal Auto', 'Corporate Auto', 'Special Auto'], dtype=object)

In [104]:
customer_data_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9137 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   int64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 785.3+ KB

In [105]:
customer_data_master['customer_lifetime_value'].isna().sum()

7

In [106]:
customer_data_master['customer_lifetime_value']=customer_data_master['customer_lifetime_value'].fillna(customer_data_master['customer_lifetime_value'].mean())

In [107]:
customer_data_master['customer_lifetime_value'].isna().sum()

0

In [108]:
customer_data_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9137 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9137 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   int64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(4), int64(1), object(6)
memory usage: 785.3+ KB

In [109]:
customer_data_master=customer_data_master.astype({'customer_lifetime_value':'int','income':'int','monthly_premium_auto':'int','total_claim_amount':'int'})

In [110]:
customer_data_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9137 entries, 0 to 9136
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9137 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9137 non-null   int64
 5   income                     9137 non-null   int64
 6   monthly_premium_auto       9137 non-null   int64
 7   number_of_open_complaints  9137 non-null   int64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   int64
dtypes: int64(5), object(6)
memory usage: 785.3+ KB

In [111]:
customer_data_master

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,182196,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,Female,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,Female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,Male,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,23405,71941,73,0,Personal Auto,Four-Door Car,198
9133,PK87824,California,Female,College,3096,21604,79,0,Corporate Auto,Four-Door Car,379
9134,TD14365,California,Male,Bachelor,8163,0,85,3,Corporate Auto,Four-Door Car,790
9135,UP19263,California,Male,College,7524,21941,96,0,Personal Auto,Four-Door Car,691
9136,Y167826,California,Male,College,2611,0,77,0,Corporate Auto,Two-Door Car,369

In [116]:
customer_data_master_duplicates=customer_data_master.duplicated().sum()

In [117]:
customer_data_master_duplicates

3

In [118]:
customer_data_master_no_duplicates= customer_data_master.drop_duplicates()
customer_data_master_no_duplicates

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,182196,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,Female,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,Female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,Male,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
9132,LA72316,California,Male,Bachelor,23405,71941,73,0,Personal Auto,Four-Door Car,198
9133,PK87824,California,Female,College,3096,21604,79,0,Corporate Auto,Four-Door Car,379
9134,TD14365,California,Male,Bachelor,8163,0,85,3,Corporate Auto,Four-Door Car,790
9135,UP19263,California,Male,College,7524,21941,96,0,Personal Auto,Four-Door Car,691
9136,Y167826,California,Male,College,2611,0,77,0,Corporate Auto,Two-Door Car,369

In [119]:
customer_data_cleaned = customer_data_master_no_duplicates.reset_index(drop=True)

In [120]:
customer_data_cleaned

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,Female,Master,182196,0,1000,0,Personal Auto,Four-Door Car,2
1,QZ44356,Arizona,Female,Bachelor,697953,0,94,0,Personal Auto,Four-Door Car,1131
2,AI49188,Nevada,Female,Bachelor,1288743,48767,108,0,Personal Auto,Two-Door Car,566
3,WW63253,California,Male,Bachelor,764586,0,106,0,Corporate Auto,SUV,529
4,GA49547,Washington,Male,High School or Below,536307,36357,68,0,Personal Auto,Four-Door Car,17
...,...,...,...,...,...,...,...,...,...,...,...
9129,LA72316,California,Male,Bachelor,23405,71941,73,0,Personal Auto,Four-Door Car,198
9130,PK87824,California,Female,College,3096,21604,79,0,Corporate Auto,Four-Door Car,379
9131,TD14365,California,Male,Bachelor,8163,0,85,3,Corporate Auto,Four-Door Car,790
9132,UP19263,California,Male,College,7524,21941,96,0,Personal Auto,Four-Door Car,691
9133,Y167826,California,Male,College,2611,0,77,0,Corporate Auto,Two-Door Car,369

In [134]:
customer_data_cleaned.to_csv('customer_data_final')

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [112]:
marketing_analysis=pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')

In [113]:
marketing_analysis

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,"4,809.22",No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.80,Four-Door Car,Medsize,A,2
1,1,KX64629,California,"2,228.53",No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.92,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,"14,947.92",No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.00,SUV,Medsize,A,2
3,3,XL78013,Oregon,"22,332.44",Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.01,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,"9,025.07",No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.93,Four-Door Car,Medsize,A,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10905,10905,FE99816,Nevada,"15,563.37",No,Premium,Bachelor,2011-01-19,Unemployed,F,...,7,Personal Auto,Personal L1,Offer3,Web,"1,214.40",Luxury Car,Medsize,A,1
10906,10906,KX53892,Oregon,"5,259.44",No,Basic,College,2011-01-06,Employed,F,...,6,Personal Auto,Personal L3,Offer2,Branch,273.02,Four-Door Car,Medsize,A,1
10907,10907,TL39050,Arizona,"23,893.30",No,Extended,Bachelor,2011-02-06,Employed,F,...,2,Corporate Auto,Corporate L3,Offer1,Web,381.31,Luxury SUV,Medsize,A,2
10908,10908,WA60547,California,"11,971.98",No,Premium,College,2011-02-13,Employed,F,...,6,Personal Auto,Personal L1,Offer1,Branch,618.29,SUV,Medsize,A,2
10909,10909,IV32877,California,"6,857.52",No,Basic,Bachelor,2011-01-08,Unemployed,M,...,3,Personal Auto,Personal L1,Offer4,Web,"1,021.72",SUV,Medsize,A,1

In [115]:
marketing_analysis.columns.tolist()

['unnamed:_0',
 'customer',
 'state',
 'customer_lifetime_value',
 'response',
 'coverage',
 'education',
 'effective_to_date',
 'employmentstatus',
 'gender',
 'income',
 'location_code',
 'marital_status',
 'monthly_premium_auto',
 'months_since_last_claim',
 'months_since_policy_inception',
 'number_of_open_complaints',
 'number_of_policies',
 'policy_type',
 'policy',
 'renew_offer_type',
 'sales_channel',
 'total_claim_amount',
 'vehicle_class',
 'vehicle_size',
 'vehicle_type',
 'month']

In [121]:
marketing_analysis.shape

(10910, 27)

In [122]:
marketing_analysis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10910 entries, 0 to 10909
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   unnamed:_0                     10910 non-null  int64
 1   customer                       10910 non-null  object
 2   state                          10910 non-null  object
 3   customer_lifetime_value        10910 non-null  float64
 4   response                       10910 non-null  object
 5   coverage                       10910 non-null  object
 6   education                      10910 non-null  object
 7   effective_to_date              10910 non-null  object
 8   employmentstatus               10910 non-null  object
 9   gender                         10910 non-null  object
 10  income                         10910 non-null  int64
 11  location_code                  10910 non-null  object
 12  marital_status                 10910 non-null  object
 13  monthly_premium_auto           10910 non-null  int64
 14  months_since_last_claim        10910 non-null  float64
 15  months_since_policy_inception  10910 non-null  int64
 16  number_of_open_complaints      10910 non-null  float64
 17  number_of_policies             10910 non-null  int64
 18  policy_type                    10910 non-null  object
 19  policy                         10910 non-null  object
 20  renew_offer_type               10910 non-null  object
 21  sales_channel                  10910 non-null  object
 22  total_claim_amount             10910 non-null  float64
 23  vehicle_class                  10910 non-null  object
 24  vehicle_size                   10910 non-null  object
 25  vehicle_type                   10910 non-null  object
 26  month                          10910 non-null  int64
dtypes: float64(4), int64(6), object(17)
memory usage: 2.2+ MB

In [123]:
marketing_analysis['monthly_premium_auto']

0         61
1         64
2        100
3         97
4        117
        ...
10905    253
10906     65
10907    201
10908    158
10909    101
Name: monthly_premium_auto, Length: 10910, dtype: int64

The total revenue generated by sales channel for particular policy type in terms of monthly premium are as follows:

In [128]:
total_revenue = marketing_analysis.pivot_table(
    index="sales_channel",
    columns="policy_type",
    values="monthly_premium_auto",
    aggfunc="sum"
)
display(total_revenue)

policy_type    Corporate Auto  Personal Auto  Special Auto
sales_channel
Agent                   82853         286725         16757
Branch                  60565         208578         11810
Call Center             42947         149286          5737
Web                     31480         113148          6883

In [127]:
marketing_analysis['policy_type'].unique()

array(['Corporate Auto', 'Personal Auto', 'Special Auto'], dtype=object)

In [130]:
marketing_analysis['customer_lifetime_value'].dtypes

dtype('float64')

In [129]:
average_customer_lifetime_value=marketing_analysis.pivot_table(
    index="gender",
    columns="education",
    values="customer_lifetime_value",
    aggfunc="mean"
)
display(average_customer_lifetime_value)

education  Bachelor  College   Doctor  High School or Below   Master
gender
F          7,874.27 7,748.82 7,328.51              8,675.22 8,157.05
M          7,703.60 8,052.46 7,415.33              8,149.69 8,168.83

The average customer lifetime value for "female" under the following education categories are as:
    a. Bachelor- 7874.27
    b. College- 7748.82
    c. Doctor - 7328.51
    d. High School or below - 8675.22
    e. Master - 8157.05
The average customer lifetime value for "male" under the following education categories are as:
    a. Bachelor- 7,703.60
    b. College- 8,052.46
    c. Doctor - 7,415.33
    d. High School or below - 8,149.69
    e. Master - 8,168.83

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [ ]:
# Your code goes here